/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BotBounty {
  export type SubmissionStruct = {
    solver: AddressLike;
    description: string;
    solutionUrl: string;
    createdAt: BigNumberish;
  };

  export type SubmissionStructOutput = [
    solver: string,
    description: string,
    solutionUrl: string,
    createdAt: bigint
  ] & {
    solver: string;
    description: string;
    solutionUrl: string;
    createdAt: bigint;
  };
}

export interface BotBountyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveSubmission"
      | "bounties"
      | "cancelExpiredBounty"
      | "createBounty"
      | "getSubmissions"
      | "nextBountyId"
      | "submitSolution"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyAwarded"
      | "BountyCancelled"
      | "BountyCreated"
      | "SubmissionCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveSubmission",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelExpiredBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmissions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextBountyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitSolution",
    values: [BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelExpiredBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextBountyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSolution",
    data: BytesLike
  ): Result;
}

export namespace BountyAwardedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    submissionId: BigNumberish,
    winner: AddressLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    submissionId: bigint,
    winner: string,
    reward: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    submissionId: bigint;
    winner: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCancelledEvent {
  export type InputTuple = [bountyId: BigNumberish, refund: BigNumberish];
  export type OutputTuple = [bountyId: bigint, refund: bigint];
  export interface OutputObject {
    bountyId: bigint;
    refund: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    creator: AddressLike,
    reward: BigNumberish,
    deadline: BigNumberish,
    title: string
  ];
  export type OutputTuple = [
    bountyId: bigint,
    creator: string,
    reward: bigint,
    deadline: bigint,
    title: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    creator: string;
    reward: bigint;
    deadline: bigint;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionCreatedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    submissionId: BigNumberish,
    solver: AddressLike
  ];
  export type OutputTuple = [
    bountyId: bigint,
    submissionId: bigint,
    solver: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    submissionId: bigint;
    solver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BotBounty extends BaseContract {
  connect(runner?: ContractRunner | null): BotBounty;
  waitForDeployment(): Promise<this>;

  interface: BotBountyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveSubmission: TypedContractMethod<
    [bountyId: BigNumberish, submissionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  bounties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, string] & {
        creator: string;
        reward: bigint;
        deadline: bigint;
        status: bigint;
        title: string;
        description: string;
      }
    ],
    "view"
  >;

  cancelExpiredBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBounty: TypedContractMethod<
    [title: string, description: string, deadline: BigNumberish],
    [bigint],
    "payable"
  >;

  getSubmissions: TypedContractMethod<
    [bountyId: BigNumberish],
    [BotBounty.SubmissionStructOutput[]],
    "view"
  >;

  nextBountyId: TypedContractMethod<[], [bigint], "view">;

  submitSolution: TypedContractMethod<
    [bountyId: BigNumberish, description: string, solutionUrl: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveSubmission"
  ): TypedContractMethod<
    [bountyId: BigNumberish, submissionId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, string] & {
        creator: string;
        reward: bigint;
        deadline: bigint;
        status: bigint;
        title: string;
        description: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelExpiredBounty"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBounty"
  ): TypedContractMethod<
    [title: string, description: string, deadline: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getSubmissions"
  ): TypedContractMethod<
    [bountyId: BigNumberish],
    [BotBounty.SubmissionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextBountyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitSolution"
  ): TypedContractMethod<
    [bountyId: BigNumberish, description: string, solutionUrl: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BountyAwarded"
  ): TypedContractEvent<
    BountyAwardedEvent.InputTuple,
    BountyAwardedEvent.OutputTuple,
    BountyAwardedEvent.OutputObject
  >;
  getEvent(
    key: "BountyCancelled"
  ): TypedContractEvent<
    BountyCancelledEvent.InputTuple,
    BountyCancelledEvent.OutputTuple,
    BountyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionCreated"
  ): TypedContractEvent<
    SubmissionCreatedEvent.InputTuple,
    SubmissionCreatedEvent.OutputTuple,
    SubmissionCreatedEvent.OutputObject
  >;

  filters: {
    "BountyAwarded(uint256,uint256,address,uint256)": TypedContractEvent<
      BountyAwardedEvent.InputTuple,
      BountyAwardedEvent.OutputTuple,
      BountyAwardedEvent.OutputObject
    >;
    BountyAwarded: TypedContractEvent<
      BountyAwardedEvent.InputTuple,
      BountyAwardedEvent.OutputTuple,
      BountyAwardedEvent.OutputObject
    >;

    "BountyCancelled(uint256,uint256)": TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;
    BountyCancelled: TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;

    "BountyCreated(uint256,address,uint256,uint64,string)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "SubmissionCreated(uint256,uint256,address)": TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;
    SubmissionCreated: TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;
  };
}
