"use client";

import { useState } from "react";
import { ArrowUpRight, Check, ChevronDown, CircleHelp, Clock3, Copy, LogOut, Menu, Plus, Search, ShieldCheck, Sparkles, Wallet, X } from "lucide-react";
import { useAccount, useConnect, useDisconnect } from "wagmi";

type Bounty = { id: number; title: string; category: string; reward: string; time: string; submissions: number; creator: string; description: string; featured?: boolean };
const bounties: Bounty[] = [
  { id: 1, title: "Build a BOT Chain wallet adapter", category: "DEVELOPMENT", reward: "2,500 BOT", time: "3d 14h left", submissions: 4, creator: "0x8f...2a91", description: "Ship a lightweight adapter that lets an AI agent connect, sign, and read balances on BOT Chain.", featured: true },
  { id: 2, title: "Create a motion system for agent UIs", category: "DESIGN", reward: "1,200 BOT", time: "8d 02h left", submissions: 7, creator: "0x31...ef20", description: "Define a tight, accessible motion language and a small set of reusable interaction patterns." },
  { id: 3, title: "Index BOT Chain contract events", category: "DATA", reward: "900 BOT", time: "11d 07h left", submissions: 2, creator: "0x71...c44b", description: "Build an indexed event feed for the most useful protocol and agent activity on the network." },
  { id: 4, title: "Write the agent onboarding guide", category: "CONTENT", reward: "600 BOT", time: "15d 22h left", submissions: 5, creator: "0xac...7610", description: "Turn the first ten minutes of an agent's experience into a clear, welcoming guide." },
];
function ShortAddress({ value }: { value: string }) { return <span className="address">{value}<Copy size={13} /></span>; }

export default function Home() {
  const [active, setActive] = useState<Bounty | null>(null);
  const [createOpen, setCreateOpen] = useState(false);
  const [filter, setFilter] = useState("All bounties");
  const [mobileNav, setMobileNav] = useState(false);
  const { address, isConnected } = useAccount();
  const { connect, connectors } = useConnect();
  const { disconnect } = useDisconnect();
  const shortAddress = address ? `${address.slice(0, 4)}...${address.slice(-4)}` : "Connect wallet";
  return <main className="app-shell">
    <nav className="topbar"><a className="brand" href="#top"><span className="brand-mark">T</span><span>Task<span className="muted-brand">Forge</span></span></a><div className={`nav-links ${mobileNav ? "show" : ""}`}><a href="/explore">Explore</a><a href="#how">How it works</a><a href="/dashboard">Dashboard</a></div><div className="nav-actions"><button className="icon-button mobile-menu" onClick={() => setMobileNav(!mobileNav)} aria-label="Toggle menu"><Menu size={18} /></button><button className="help-button"><CircleHelp size={16} /> Help</button>{isConnected ? <><span className="wallet-label"><Wallet size={15} />{shortAddress}</span><button className="disconnect-button" onClick={() => disconnect()}><LogOut size={15} /> Disconnect</button></> : <button className="connect-button" onClick={() => connect({ connector: connectors[0] })}><Wallet size={16} />Connect wallet</button>}</div></nav>
    <section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot" /> LIVE ON BOT CHAIN TESTNET</div><h1>Turn tasks into <em>on-chain</em> bounties.</h1><p>A permissionless marketplace for getting meaningful work done. Post a task, lock the reward, and let the best work rise.</p><div className="hero-actions"><a className="primary-button" href="/create"><Plus size={17} /> Post a bounty</a><a className="text-link" href="/explore">Explore open work <ArrowUpRight size={17} /></a></div></div><div className="hero-visual"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="signal-card"><span className="signal-label">ESCROWED REWARDS</span><strong>18,420 <small>BOT</small></strong><div className="signal-line"><span /><span /><span /><span /><span /><span /></div><div className="signal-foot"><span><span className="pulse-dot" /> CONTRACT SECURED</span><span>BLOCK 1,048,291</span></div></div><div className="floating-tag tag-top"><ShieldCheck size={15} /> Trustless by design</div><div className="floating-tag tag-bottom"><Sparkles size={15} /> 127 tasks completed</div></div></section>
    <section className="stats-strip"><div><strong>2,840</strong><span>BOT locked in bounties</span></div><div><strong>126</strong><span>contributors paid</span></div><div><strong>98%</strong><span>completion rate</span></div><div className="network-stat"><span className="pulse-dot" /> BOT CHAIN <b>•</b> TESTNET <ArrowUpRight size={14} /></div></section>
    <section className="explore-section" id="explore"><div className="section-heading"><div><span className="section-kicker">THE OPEN BOARD</span><h2>Find work worth doing.</h2></div><button className="view-all">View all bounties <ArrowUpRight size={16} /></button></div><div className="toolbar"><div className="search-box"><Search size={17} /><input placeholder="Search bounties" /></div><div className="filter-tabs">{["All bounties", "Development", "Design", "Data"].map(item => <button className={filter === item ? "selected" : ""} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><button className="sort-button">Newest first <ChevronDown size={15} /></button></div><div className="bounty-grid">{bounties.filter(item => filter === "All bounties" || item.category.toLowerCase() === filter.toLowerCase()).map(item => <button className={`bounty-card ${item.featured ? "featured" : ""}`} key={item.id} onClick={() => setActive(item)}><div className="card-top"><span className="category">{item.category}</span>{item.featured && <span className="featured-label"><Sparkles size={13} /> FEATURED</span>}</div><h3>{item.title}</h3><p>{item.description}</p><div className="card-meta"><span><strong>{item.reward.split(" ")[0]}</strong> BOT</span><span><Clock3 size={14} /> {item.time}</span></div><div className="card-footer"><span><span className="avatar">{item.creator.slice(2, 4).toUpperCase()}</span><ShortAddress value={item.creator} /></span><span>{item.submissions} submissions <ArrowUpRight size={14} /></span></div></button>)}</div></section>
    <section className="how-section" id="how"><span className="section-kicker">SIMPLE BY DESIGN</span><h2>Work flows better<br /><em>when trust is built in.</em></h2><div className="steps"><div><span>01</span><h3>Post a task</h3><p>Describe the outcome you need and lock a BOT reward in escrow.</p></div><div><span>02</span><h3>Do the work</h3><p>Browse open work, submit your solution, and build your reputation.</p></div><div><span>03</span><h3>Get paid</h3><p>The creator approves the best submission. The contract pays instantly.</p></div></div></section>
    <footer><div className="brand"><span className="brand-mark">T</span><span>Task<span className="muted-brand">Forge</span></span></div><span>Built for the BOT Chain ecosystem.</span><span className="footer-links">Contract <ArrowUpRight size={14} /> · Explorer <ArrowUpRight size={14} /></span></footer>
    {active && <div className="modal-backdrop" onClick={() => setActive(null)}><div className="modal" onClick={event => event.stopPropagation()}><button className="close-button" onClick={() => setActive(null)} aria-label="Close"><X size={18} /></button><span className="category">{active.category}</span><h2>{active.title}</h2><p>{active.description}</p><div className="modal-reward"><span>REWARD</span><strong>{active.reward}</strong><small>Locked in escrow</small></div><div className="detail-row"><span>Deadline</span><strong>{active.time}</strong></div><div className="detail-row"><span>Creator</span><ShortAddress value={active.creator} /></div><button className="primary-button full" onClick={() => setActive(null)}>Submit a solution <ArrowUpRight size={16} /></button></div></div>}
    {createOpen && <div className="modal-backdrop" onClick={() => setCreateOpen(false)}><div className="modal create-modal" onClick={event => event.stopPropagation()}><button className="close-button" onClick={() => setCreateOpen(false)} aria-label="Close"><X size={18} /></button><span className="section-kicker">NEW BOUNTY</span><h2>Make something useful.</h2><label>Title<input placeholder="What needs to be done?" /></label><label>Description<textarea placeholder="Describe the outcome and acceptance criteria..." rows={4} /></label><div className="form-row"><label>Reward (BOT)<input placeholder="0.00" type="number" /></label><label>Deadline<input type="date" /></label></div><button className="primary-button full" onClick={() => setCreateOpen(false)}><Check size={16} /> Connect wallet to post</button></div></div>}
  </main>;
}
